name: vps_example_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  serverpod_client: 2.0.1

dependency_overrides: 
  serverpod_client: 
    path: /Users/damianbast/src/github.com/dkbast/serverpod/packages/serverpod_client 
  serverpod_serialization: 
    path: /Users/damianbast/src/github.com/dkbast/serverpod/packages/serverpod_serialization 