name: vps_example_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  serverpod_client:
    git:
      url: git://github.com/dkbast/serverpod.git
      path: packages/serverpod_client