name: vps_example_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  serverpod: 2.0.1

dev_dependencies:
  lints: '>=3.0.0 <5.0.0'

dependency_overrides: 
  serverpod: 
    path: /Users/damianbast/src/github.com/dkbast/serverpod/packages/serverpod 
  serverpod_serialization: 
    path: /Users/damianbast/src/github.com/dkbast/serverpod/packages/serverpod_serialization 
  serverpod_shared: 
    path: /Users/damianbast/src/github.com/dkbast/serverpod/packages/serverpod_shared 